# Generated by Django 4.0 on 2022-02-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=450)),
                ('image', models.ImageField(upload_to='uploads/Tours/')),
            ],
        ),
    ]
