# Generated by Django 4.0 on 2022-02-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_bookings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
