# Generated by Django 4.0 on 2022-02-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
