# Generated by Django 4.0 on 2022-02-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
