# Generated by Django 4.0.4 on 2022-04-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safari',
            old_name='Name',
            new_name='name',
        ),
    ]
